### ISSUE TITLE
fails to build with text-2.1.2

### ISSUE THREAD

**Issue by juhp** [zgrannan/rest#45]
For Stackage Nightly with ghc-9.10.2

```
       Building library 'testlib' for rest-rewrite-0.4.4...                                                    12:58:25 [485/954403]
       [1 of 7] Compiling Language.REST.ConcreteOC                                                                                  
       [2 of 7] Compiling Language.REST.ProofGen                  
       [3 of 7] Compiling MultisetOrdering
       [4 of 7] Compiling Nat                                     
       /home/curators/work/unpack-dir/unpacked/rest-rewrite-0.4.4-b09d3ab6fa4e5924f3eb712406c8812e959747f47b4621db3e3509ffaea66c44/t
estlib/Nat.hs:49:24: error: [GHC-87543]      
           Ambiguous occurrence ‘show’.                
           It could refer to                                      
              either ‘Prelude.show’,                       
                     imported from ‘Prelude’ at testlib/Nat.hs:7:8-10                                                               
                     (and originally defined in ‘ghc-internal-9.1002.0:GHC.Internal.Show’),                                         
                  or ‘Data.Text.show’,             
                     imported from ‘Data.Text’ at testlib/Nat.hs:10:1-16.                                                           
          |                                                       
       49 |     showInt t = pack . show <$> termToInt t
          |                        ^^^^              
                                                                  
       /home/curators/work/unpack-dir/unpacked/rest-rewrite-0.4.4-b09d3ab6fa4e5924f3eb712406c8812e959747f47b4621db3e3509ffaea66c44/t
estlib/Nat.hs:99:24: error: [GHC-87543]     
           Ambiguous occurrence ‘show’.              
           It could refer to                                      
              either ‘Prelude.show’,              
                     imported from ‘Prelude’ at testlib/Nat.hs:7:8-10                                                               
                     (and originally defined in ‘ghc-internal-9.1002.0:GHC.Internal.Show’),                                         
                  or ‘Data.Text.show’,         
                     imported from ‘Data.Text’ at testlib/Nat.hs:10:1-16.                                                           
          |                                                                                                                         
       99 |     Left err -> error (show err)          
          |                        ^^^^ 
```

**Comment by facundominguez** [comment]
Thanks @juhp. There's `rest-rewrite-0.4.5` now, that should fix it.
